name: energy_assistant_app
description: "Energy Assistant - Hitachi Energy PV Calculator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.1.0
  intl: ^0.18.1
  pdf: ^3.10.4
  printing: ^5.11.1
  path_provider: ^2.1.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/panel_sim.html
    - assets/hitachi_logo.png
