name: energy_strategist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  webview_flutter: ^4.7.0 # Added WebView dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/panel_sim.html
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica/Helvetica.ttf
