import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'models/hitachi_product.dart';

final hitachiProductsProvider = Provider<List<HitachiProduct>>((ref) {
  return [
    const HitachiProduct(
      type: ProductType.panel,
      name: 'Monocrystalline 450W',
      power: 0.45,
      price: 800,
      efficiency: 21.5,
      features: ['Mono-PERC', '25 lat gwarancji', 'Anti-reflective'],
      imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=300&fit=crop',
      category: '☀️ PANELE PV',
      color: Colors.orange,
    ),
    const HitachiProduct(
      type: ProductType.panel,
      name: 'Bifacial 550W',
      power: 0.55,
      price: 1100,
      efficiency: 22.8,
      features: ['Bifacial', 'Glass-glass', 'Premium efficiency'],
      imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=300&fit=crop',
      category: '☀️ PANELE PV',
      color: Colors.orange,
    ),
    const HitachiProduct(
      type: ProductType.inverter,
      name: 'ABB UNO-DM-3.3-TL-PLUS',
      power: 3.3,
      price: 3500,
      efficiency: 97.3,
      features: ['Monofazowy', 'Wewnętrzny', 'WiFi'],
      imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=300&fit=crop',
      category: '🔄 INWERTERY',
      color: Colors.blue,
    ),
    const HitachiProduct(
      type: ProductType.inverter,
      name: 'ABB TRIO-8.5-TL-OUTD',
      power: 8.5,
      price: 6800,
      efficiency: 98.1,
      features: ['Trójfazowy', 'Zewnętrzny', 'Monitoring'],
      imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=300&fit=crop',
      category: '🔄 INWERTERY',
      color: Colors.blue,
    ),
    const HitachiProduct(
      type: ProductType.inverter,
      name: 'ABB TRIO-20.0-TL-OUTD',
      power: 20.0,
      price: 12500,
      efficiency: 98.3,
      features: ['Trójfazowy', 'Przemysłowy', 'SCADA'],
      imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=300&fit=crop',
      category: '🔄 INWERTERY',
      color: Colors.blue,
    ),
    const HitachiProduct(
      type: ProductType.battery,
      name: 'ABB REACT 2',
      capacity: 9.5,
      price: 19000,
      cycles: 6000,
      features: ['LiFePO4', 'AC coupled', 'Backup'],
      imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop',
      category: '🔋 MAGAZYN',
      color: Colors.green,
    ),
    const HitachiProduct(
      type: ProductType.battery,
      name: 'Hitachi Energy PowerStore 20',
      capacity: 20.0,
      price: 38000,
      cycles: 8000,
      features: ['Enterprise', 'Grid services', 'Scalable'],
      imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop',
      category: '🔋 MAGAZYN',
      color: Colors.green,
    ),
    const HitachiProduct(
      type: ProductType.monitoring,
      name: 'ABB Monitoring Portal',
      price: 1200,
      features: ['Zdalny monitoring', 'Analiza wydajności', 'Alerty SMS/email'],
      imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
      category: '📊 MONITORING',
      color: Colors.purple,
    ),
    const HitachiProduct(
      type: ProductType.monitoring,
      name: 'Hitachi Energy Management System',
      price: 2500,
      features: ['AI optimization', 'Predykcja produkcji', 'Smart Grid'],
      imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
      category: '📊 MONITORING',
      color: Colors.purple,
    ),
  ];
});